NUMBER_OF_BUSHES = 20
NUMBER_OF_MINES = 20
NUMBER_OF_FLOWERS = 10
NUMBER_OF_GRASS = 10
BACKGROUND_LIGHT_COLOR = (190, 229, 176)
BACKGROUND_DARK_COLOR = (0, 0, 0)
GRID_COLOR = (46, 139, 87)
TEXT_COLOR = (255, 255, 255)
WELCOME_MESSAGE1 = "Welcome to The Flag game."
WELCOME_MESSAGE2 = "Have Fun!"
NUMBER_OF_ROWS = 25
NUMBER_OF_COLUMNS = 50
WINDOW_WIDTH = 25
WINDOW_HEIGHT = 50
SIZE = 25
TRANSPARENT = (0, 0, 0, 0)

SOLIDER_PNG_SIZE = (4, 2)  # 4 height, 2 width
SOLIDER_STARTING_PLACE = (0, 0)  # x = 0, y = 0

FLAG_SIZE = (3, 4)  # 3 height, 4 width
FLAG_LOCATION = (21, 47)

MINES_SIZE = (1, 3)  # 1 height, 3 width

WIN_MESSAGE = "You won!"
LOSE_MESSAGE = "You lost!"

SOLIDER_LEGS = 'solider legs'
SOLIDER_BODY = 'solider body'
MINES = 'mine'
FLAG = 'flag'
EMPTY = '0'
